### ISSUE TITLE
Camera calibration

### ISSUE THREAD

**Issue by KUTuaNithid** [KUTuaNithid/phenorobot#1]
- To calibrate the camera for image processing process.

Camera model: [ELP-960P2CAM-V90-VC (fisheye)](https://www.amazon.com/ELP-Industrial-Application-Synchronized-ELP-960P2CAM-V90-VC/dp/B078TDLHCP)
Synchornous

## Sub-task

1. Split frame and rerepublish
2. Use ros calibration package

**Comment by KUTuaNithid** [comment]
To split and image 
https://github.com/mdkennedy3/elp-synchronized-stereo-camera-ros-pkg

Ros calibration package
http://wiki.ros.org/camera_calibration

**Comment by KUTuaNithid** [comment]
From Dr. Pished, we need to get an undistorted image to verify the result.

Stereo rectify code https://github.com/ShreyasSkandanS/stereo_fisheye_rectify

**Comment by KUTuaNithid** [comment]
Undistroed image https://drive.google.com/drive/folders/1KbHwlqABTmt-Hi_dl7M1tT5xolaNWM-J?usp=sharing

**Comment by KUTuaNithid** [comment]
Adjusted lense on camera hardware to make the right lense clear

Recalibration get error
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/camera_calibration/camera_calibrator.py", line 269, in on_mouse
    self.c.do_calibration()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 1231, in do_calibration
    self.cal_fromcorners(self.good_corners)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 1004, in cal_fromcorners
    flags = flags)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/calib3d/src/fisheye.cpp:859: error: (-215:Assertion failed) D1.empty() || (D1.total() == 4) in function 'stereoCalibrate'

**Comment by KUTuaNithid** [comment]
Need to checkout from source -> https://github.com/ros-perception/image_pipeline/tree/melodic
For 2560x960 error
```
abs_max < threshold in function 'stereoCalibrate'
```

Need to set resolution to lower

P[0, 0] still not equal.
